[package]
name = "pub_hubs"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

[features]
real_credentials = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Error handling
# note:  anyhow is also used by cargo
thiserror = "1.0"
anyhow = "1.0"

# serde
serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.8"
serde_json = "1.0"
serde_urlencoded = "0.7"
rmp-serde = "1.1"

# Database interaction
rusqlite = {version = "0.27.0", features = ["bundled"]}
rand = "0.8"

# IRMA interaction
regex = "1.5"
qrcode = "0.12"
chrono = {version="0.4", default_features = false, features = ["clock"]}
# note: we don't use chrono 0.4's default features, because it includes oldtime,
#       which pulls in time 0.1, which has a vulnerability (viz. RUSTSEC-2020-0071)
async-recursion = "1.0"

# Web dependencies
tokio = {version = "1.17", features = ["rt", "macros", "rt-multi-thread", "sync", "time"]}
hyper = {version= "0.14", features= ["server", "client", "http1", "stream" ]}
hyper-tls = "0.5"
url = "2.2" 
uuid = {version = "1.1", features = ["v4"]}
env_logger = "0.9"
log = "0.4"
jsonwebtoken = "8.1"  # uses non RustCrypto - perhaps replace?

# RustCrypto packages
hmac = "0.12"
pbkdf2 = "0.11"
sha2 = "0.10"
base64ct = {version = "1.5", features = ["alloc"]}
chacha20poly1305 = "0.10"
aead = "0.5"
generic-array = "0.14"
typenum = "1.15"

#iLab crates
hairy = "0.1.2"
expry = "0.1.2"

[dev-dependencies]
tempfile = "3.3"


