[package]
name = "pubhubs"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

[features]
real_credentials = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Error handling
# note:  anyhow is also used by cargo
thiserror = "1.0"
anyhow = "1.0"

# serde
serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
serde_json = "1.0"
serde_urlencoded = "0.7"
rmp-serde = "1.1"

# Database interaction
rusqlite = {version = "0.28.0", features = ["bundled"]}
rand = "0.8"

# for ed25519_dalek, see https://stackoverflow.com/questions/65562447/the-trait-rand-corecryptorng-is-not-implemented-for-osrng
#rand_07 = { package = "rand", version = "0.7" }


# Yivi interaction
regex = "1.5"
qrcode = "0.12"
chrono = {version="0.4", default_features = false, features = ["clock"]}
# note: we don't use chrono 0.4's default features, because it includes oldtime,
#       which pulls in time 0.1, which has a vulnerability (viz. RUSTSEC-2020-0071)
async-recursion = "1.0"

# Web dependencies
tokio = {version = "1.23", features = ["rt", "macros", "rt-multi-thread", "sync", "time"]}
tokio-test = "0.4"
hyper = {version= "0.14", features= ["server", "client", "http1", "stream" ]}
hyper-tls = "0.5"
url = "2.2" 
bytes = "1"
http = "0.2"
uuid = {version = "1.1", features = ["v4"]}
env_logger = "0.10"
log = "0.4"
jsonwebtoken = "8.1"  # uses non RustCrypto - perhaps replace?
actix-web = "4.3"
actix-files = "0.6"
# Proxying requests to Yivi and connection check
awc = { version = "3.1", features = ["openssl"] }

# RustCrypto packages
hmac = "0.12"
sha2 = "0.10"
base64ct = {version = "1.6", features = ["alloc"]}
base16ct = {version = "0.2", features = ["alloc"]} # hex
chacha20poly1305 = "0.10"
aead = "0.5"
generic-array = "0.14"
typenum = "1.15"
ed25519 = {version = "2.1", features = ["pkcs8", "alloc", "pem"]}
ed25519-dalek = "1.0"
# Constant time operations to prevent timing attacks.
subtle = "2.4"

#metrics
prometheus = "0.13"
lazy_static = "1.4"
strum_macros = "0.24"
futures = "0.3"

#iLab crates
hairy = "0.1.2"
expry = "0.1.2"

[dev-dependencies]
tempfile = "3.4"
