[package]
name = "pub_hubs"
version = "0.1.0"
edition = "2021"

[features]
real_credentials = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Error handling
# note:  anyhow is also used by cargo
anyhow = "1.0"

serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.8"

# Database interaction
rusqlite = {version = "0.27.0", features = ["bundled"]}
rand = "0.8"

# IRMA interaction
regex = "1.5"
qrcode = "0.12"
chrono = "0.4"
async-recursion = "1.0"

# Web dependencies
tokio = {version = "1.17", features = ["rt", "macros", "rt-multi-thread", "sync", "time"]}
hyper = {version= "0.14", features= ["server", "client", "http1", "stream" ]}
hyper-tls = "0.5"
uuid = {version = "1.1", features = ["v4"]}
env_logger = "0.9"
log = "0.4"
serde_json = "1.0"
jsonwebtoken = "8.1"

# Used for oauth
pbkdf2 = "0.11"
serde_urlencoded = "0.7"
base64 = "0.13"
openssl = "0.10"

#sign cookies
hmac = "0.12"
sha2 = "0.10"

#iLab crates
hairy = "0.1.2"
expry = "0.1.2"

[dev-dependencies]
tempfile = "3.3"
