# if url is not set, pubhubs will attempt to autodetect your public ip (if you have one)
# if url is set, it must have a trailing slash ('/')
# url: url-pointing-to-this-machine-reachable-from-your-phone.example.com/

database_location: dev.db  # if not set, in memory database is used

irma:
  server_url: http://localhost:8088

pep: {
  # libpep_location: /path/to/libpepcli
}

admins:
  - admin@example.com
