## If url is not set, it will be http://localhost:port-binded-to/.  Must end with a slash ('/').
# url: https://some-server.com/

## The url used by the yivi app to contact PubHubs Central.  To use the same url as 'url', use
# url_for_yivi_app: !same
## To autodetect your public IP address, and try that, use:
url_for_yivi_app: !autodetect
## To configure a URL manually, use
#url_for_yivi_app: !manual https://some-server.com/ 

database_location: dev.db  # if not set, in memory database is used

yivi:
  requestor_api_url: http://localhost:8088

pep: {
  # libpep_location: /path/to/libpepcli
}

# Allowed contexts for embedding the login-flow. This will be the PubHubs global client(8080), allowing it to embed
# itself, in case we need to authenticate for a specific hub and are not (yet) logged in globally.
allowed_embedding_contexts: [localhost:8080]

admins:
  - admin@example.com
