version: '3'

services:
  matrix:
    container_name: test_hub
    build:
      context: $PWD
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      - HUB_SECRET
      - SYNAPSE_CONFIG_DIR=/data
      - AUTHLIB_INSECURE_TRANSPORT=for_testing_only_of_course
    volumes:
      - $PWD/matrix_test_config:/data:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"

  livekit:
    image: livekit/livekit-server:latest
    command: --dev --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882"
      - "50100-50200:50100-50200"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
