version: '3'
services:
  irma:
    container_name: irma
    build:
      context: $PWD
      dockerfile: docker_irma/Dockerfile
    ports:
      - "8088:8088"
  element:
    container_name: element
    image: registry.science.ru.nl/ilab/pubhubs-element-web/pubhubs-element-web:main
    ports:
      - "8800:80"
    volumes:
      - ./element/config.json:/app/config.json:ro


