variables:
  DOCKER_DRIVER: overlay # faster docker builds, see https://gitlab.com/gitlab-org/gitlab-ce/issues/21374

before_script:
  - ENV_FILE="pubhubs/.${CI_COMMIT_REF_NAME}.env"
  - test -f ${ENV_FILE} && source ${ENV_FILE} # 'source ${ENV_FILE} || true' does not work on busybox

# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
stages: # List of stages for jobs, and their order of execution
  - build
  - build-images
  - deploy

clippy:
  stage: build
  tags:
    - docker
  image: registry.science.ru.nl/ilab/docker-build/rust-nightly:main
  script:
    - cd pubhubs
    # twice, because sometimes clippy has hard errors, and won't produce the report
    - cargo +nightly clippy
    - cargo +nightly clippy --message-format=json | gitlab-report -p clippy > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: pubhubs/gl-code-quality-report.json
    expire_in: 1 week
  rules:
    - if: "$CODE_QUALITY_DISABLED"
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
  cache:
    key: "${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}"
    paths:
      - pubhubs/target/

unit-test-rust-code:
  stage: build
  tags:
    - docker
  image: registry.science.ru.nl/ilab/docker-build/rust-stable:main
  script:
    - cd pubhubs
    - env RUST_BACKTRACE=full cargo +stable test --no-fail-fast -- -Z unstable-options --format json | gitlab-report -p test > report.xml
  artifacts:
    reports:
      junit: pubhubs/report.xml
    expire_in: 1 week
  cache:
    key: "${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}"
    paths:
      - pubhubs/target/

cargo-deny:
  stage: build
  tags:
    - docker
  image: registry.science.ru.nl/ilab/docker-build/rust-stable:main
  script:
    - cd pubhubs
    - cargo deny check

build-pubhubs-image:
  stage: build-images
  only:
    - main
    - stable
  needs:
    - unit-test-rust-code
  tags:
    - docker
  image: docker:stable
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/pubhubs:${CI_COMMIT_REF_NAME}
  script:
    - cd pubhubs
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg "CARGO_FEATURES=${CARGO_FEATURES}" -f Dockerfile -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}

deploy-main:
  stage: deploy
  only:
    - main
  environment: $CI_COMMIT_REF_NAME
  tags: [docker]
  image: ubuntu:rolling
  script:
    - cd pubhubs
    - apt update
    - apt install -y openssh-client
    - chmod 600 $ILAB_VM_TRIGGER_UPDATE_KEY
    - ssh -o UserKnownHostsFile=$ILAB_VM_TRIGGER_UPDATE_KNOWN_HOSTS $ILAB_VM_TRIGGER_UPDATE_USER@$ILAB_VM_TRIGGER_UPDATE_HOST_MAIN -i $ILAB_VM_TRIGGER_UPDATE_KEY docker-pubhubs-main

deploy-stable:
  stage: deploy
  only:
    - stable
  environment: $CI_COMMIT_REF_NAME
  tags: [docker]
  image: ubuntu:rolling
  script:
    - cd pubhubs
    - apt update
    - apt install -y openssh-client
    - chmod 600 $ILAB_VM_TRIGGER_UPDATE_KEY
    - ssh -o UserKnownHostsFile=$ILAB_VM_TRIGGER_UPDATE_KNOWN_HOSTS $ILAB_VM_TRIGGER_UPDATE_USER@$ILAB_VM_TRIGGER_UPDATE_HOST_STABLE -i $ILAB_VM_TRIGGER_UPDATE_KEY docker-pubhubs-stable

unit-test-build-script:
  stage: build
  tags:
    - docker
  image: python:latest
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python3 start_test_setup.py test

unit-test-hub: # This job runs in the test stage.
  stage: build
  tags:
    - docker
  image: python:latest
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script: #install libpepcli
    - python --version # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install unittest-xml-reporting
    - apt update && apt install -y lsb-release
    - sh -c 'printf "deb http://packages.bitpowder.com/debian-%s main core\n" `lsb_release -cs`' | tee /etc/apt/sources.list.d/bitpowder-repo.list
    - curl -L https://bitpowder.com/packages/linux-packages.gpg | tee /etc/apt/trusted.gpg.d/bitpowder.asc
    - apt-get update && apt-get install -y pepcli
  script:
    - cd pubhubs_hub
    - pip install --upgrade -r requirements.txt
    - python -m xmlrunner discover -p '*_test.py' --output-file report.xml
    # Pip's cache doesn't store the python packages
    # https://pip.pypa.io/en/stable/reference/pip_install/#caching
    #
    # If you want to also cache the installed packages, you have to install
    # them in a virtualenv and cache it as well.
  cache:
    paths:
      - pubhubs_hub/.cache/pip
      - pubhubs_hub/venv/
  artifacts:
    reports:
      junit: pubhubs_hub/report.xml
    expire_in: 1 week

build-image-hub:
  stage: build-images
  only:
    - main
    - stable
  needs:
    - unit-test-hub
  tags:
    - docker
  image: docker:stable
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/pubhubs_hub:${CI_COMMIT_REF_NAME}
  script:
    - cd pubhubs_hub
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - DOCKER_BUILDKIT=1 docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}

deploy-main-hub:
  stage: deploy
  only:
    - main
  environment: $CI_COMMIT_REF_NAME
  tags: [docker]
  image: registry.science.ru.nl/ilab/docker-build/ubuntu-iso:main
  script:
    - cd pubhubs_hub
    - chmod 600 $ILAB_VM_TRIGGER_UPDATE_KEY
    - ssh -o UserKnownHostsFile=$ILAB_VM_TRIGGER_UPDATE_KNOWN_HOSTS $ILAB_VM_TRIGGER_UPDATE_USER@$ILAB_VM_TRIGGER_UPDATE_HOST_MAIN -i $ILAB_VM_TRIGGER_UPDATE_KEY docker-testhub-matrix-main

deploy-stable-hub:
  stage: deploy
  only:
    - stable
  environment: $CI_COMMIT_REF_NAME
  tags: [docker]
  image: registry.science.ru.nl/ilab/docker-build/ubuntu-iso:main
  script:
    - cd pubhubs_hub
    - chmod 600 $ILAB_VM_TRIGGER_UPDATE_KEY
    - ssh -o UserKnownHostsFile=$ILAB_VM_TRIGGER_UPDATE_KNOWN_HOSTS $ILAB_VM_TRIGGER_UPDATE_USER@$ILAB_VM_TRIGGER_UPDATE_HOST_STABLE -i $ILAB_VM_TRIGGER_UPDATE_KEY docker-testhub-matrix-stable

unit-test-client:
  stage: build
  tags: [docker]
  image: node:latest
  before_script:
    - cd hub-client
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

build-client:
  stage: build-images
  only:
    - main
    - stable
  needs:
    - unit-test-client
  tags:
    - docker
  image: docker:stable
  variables:
    CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/pubhubs_client:${CI_COMMIT_REF_NAME}
  script:
    - cd hub-client
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - DOCKER_BUILDKIT=1 docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}