version: '3'
services:
  pubhubs_hub:
    image: registry.science.ru.nl/ilab/pubhubs_canonical/pubhubs_hub:main
    ports:
      - '8008:8008'
    environment:
      - HUB_SECRET=changeme
      - SYNAPSE_CONFIG_DIR=/data
      # Only for localhost testing
      #- AUTHLIB_INSECURE_TRANSPORT=for_testing_only_of_course
    volumes:
      #- $PWD/pubhubs_hub/matrix_test_config:/data:rw
       - <absolute_path>/hub:/data:rw
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    
  pubhubs_client:
    image: registry.science.ru.nl/ilab/pubhubs_canonical/pubhubs_client:main
    ports:
      - '8800:8800'
    environment:
      - BAR_URL=frame-ancestors https://main.pubhubs.ihub.ru.nl/
      - HUB_URL=changeme                                                            
      - PARENT_URL=https://main.pubhubs.ihub.ru.nl/
    depends_on:
      - pubhubs_hub
